taxi-management:
  allowed-origins: http://localhost:4200
  database-ip: localhost
spring:
  datasource:
    url: jdbc:mariadb://${taxi-management.database-ip}:3306/taxi_management
    username: root
    password: password
  liquibase:
    change-log: db/changelog/db.changelog-initial.xml
  jpa:
    # should be turned off for performance (and scalability) reasons
    # see https://stackoverflow.com/a/48222934/3012347
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
