spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/taxi_management
    username: root
    password: password
  liquibase:
    change-log: db/changelog/db.changelog-initial.xml
  jpa:
    hibernate:
      ddl-auto: validate