openapi: 3.0.3
info:
  title: Taxi Management API
  version: 1.0.0
servers:
- url: http://localhost:3000
tags:
- description: Operations about taxis which are used for a shift
  name: taxi
- description: Operations about drivers of a shift
  name: driver
- description: Operations about start point and destination of a trip
  name: location
- description: Operations about customers which can be part of trip
  name: customer
- description: Operations about shifts done by drivers in taxis
  name: shift
paths:
  /taxis:
    $ref: 'paths/taxis.yaml'
  /drivers:
    $ref: 'paths/drivers.yaml'
  /drivers/{id}:
    $ref: 'paths/drivers_driver-id.yaml'
  /locations:
    $ref: 'paths/locations.yaml'
  /customers:
    $ref: 'paths/customers.yaml'
  /shifts:
    $ref: 'paths/shifts.yaml'
  /shifts/{shift-id}:
    $ref: 'paths/shifts_shift-id.yaml'
  /shifts/{shift-id}/trips:
    $ref: 'paths/shifts_shift-id_trips.yaml'
  /shifts/{shift-id}/trips/{trip-id}:
    $ref: 'paths/shifts_shift-id_trips_trip-id.yaml'
