version: '3.9'

services:
  mariadb:
    # supported version of host limited to 10.3
    # therefore development version is set to the same
    image: mariadb:10.3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=taxi_management